use crate::core::database::models::{Cluster, Config, Job, Status};
use serde_json;

// Generate sample data for testing
pub fn generate_sample_data() -> (Vec<Job>, Vec<Config>, Vec<Cluster>) {
  let clusters = vec![
    Cluster {
      id: 1,
      cluster_name: "HPC-GPU-Cluster".to_string(),
      scheduler: crate::core::database::models::Scheduler::Slurm,
      max_jobs: None,
    },
    Cluster {
      id: 2,
      cluster_name: "CPU-Cluster".to_string(),
      scheduler: crate::core::database::models::Scheduler::Pbs,
      max_jobs: None,
    },
    Cluster {
      id: 3,
      cluster_name: "Local-Dev".to_string(),
      scheduler: crate::core::database::models::Scheduler::Local,
      max_jobs: None,
    },
  ];

  let configs = vec![
    Config {
      id: 1,
      config_name: "A100-80GB-8GPU".to_string(),
      cluster_id: 1,
      flags: serde_json::from_str("null").unwrap(),
      env: serde_json::from_str("null").unwrap(),
    },
    Config {
      id: 2,
      config_name: "V100-32GB-4GPU".to_string(),
      cluster_id: 1,
      flags: serde_json::from_str("null").unwrap(),
      env: serde_json::from_str("null").unwrap(),
    },
    Config {
      id: 3,
      config_name: "CPU-128Core-512GB".to_string(),
      cluster_id: 2,
      flags: serde_json::from_str("null").unwrap(),
      env: serde_json::from_str("null").unwrap(),
    },
    Config {
      id: 4,
      config_name: "CPU-64Core-256GB".to_string(),
      cluster_id: 2,
      flags: serde_json::from_str("null").unwrap(),
      env: serde_json::from_str("null").unwrap(),
    },
    Config {
      id: 5,
      config_name: "Local-Dev-Config".to_string(),
      cluster_id: 3,
      flags: serde_json::from_str("null").unwrap(),
      env: serde_json::from_str("null").unwrap(),
    },
  ];

  let base_time = 1730000000; // Base timestamp
  let jobs = vec![
        // Completed jobs
        Job {
            id: 1,
            job_name: "llama3-finetune-medical".to_string(),
            config_id: 1,
            submit_time: Some(base_time),
            directory: "/scratch/user/experiments/llama3_medical/run_001".to_string(),
            command: "python train.py --model llama3-70b --dataset medical_qa --epochs 10".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Completed,
            job_id: Some("slurm_4891234".to_string()),
            end_time: Some(base_time + 43200),
            // FIXME exit_code: Some(0),
            archived: None,
        },
        Job {
            id: 2,
            job_name: "bert-sentiment-twitter".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 1000),
            directory: "/scratch/user/nlp/bert_sentiment/exp_042".to_string(),
            command: "python sentiment_analysis.py --model bert-large --data twitter_2024".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Completed,
            job_id: Some("slurm_4891235".to_string()),
            end_time: Some(base_time + 7200),
            // FIXME exit_code: Some(0),
            archived: None,
        },
        Job {
            id: 3,
            job_name: "stable-diffusion-art-gen".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 5000),
            directory: "/scratch/user/vision/stable_diff/gen_batch_15".to_string(),
            command: "python generate.py --model sdxl --prompts art_dataset.json --samples 10000".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Completed,
            job_id: Some("slurm_4891240".to_string()),
            end_time: Some(base_time + 14400),
            // FIXME exit_code: Some(0),
            archived: None,
        },
        Job {
            id: 4,
            job_name: "resnet-imagenet-baseline".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 8000),
            directory: "/scratch/user/cv/resnet/baseline_v2".to_string(),
            command: "python train_resnet.py --depth 152 --dataset imagenet --lr 0.1".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Completed,
            job_id: Some("slurm_4891245".to_string()),
            end_time: Some(base_time + 28800),
            // FIXME exit_code: Some(0),
            archived: Some(1),
        },
        Job {
            id: 5,
            job_name: "quantum-simulation-h2o".to_string(),
            config_id: 3,
            submit_time: Some(base_time + 10000),
            directory: "/scratch/user/quantum/simulations/water_molecule".to_string(),
            command: "mpirun -np 128 ./quantum_sim --molecule H2O --basis ccpvtz".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Completed,
            job_id: Some("pbs_987654".to_string()),
            end_time: Some(base_time + 86400),
            // FIXME exit_code: Some(0),
            archived: None,
        },
        // Failed jobs
        Job {
            id: 6,
            job_name: "gpt4-replication-attempt".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 12000),
            directory: "/scratch/user/llm/gpt4_replica/trial_003".to_string(),
            command: "python train_gpt.py --params 1.76T --ctx_len 32768".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Failed,
            job_id: Some("slurm_4891250".to_string()),
            end_time: Some(base_time + 15000),
            // FIXME exit_code: Some(137), // OOM killed
            archived: None,
        },
        Job {
            id: 7,
            job_name: "molecular-dynamics-protein".to_string(),
            config_id: 3,
            submit_time: Some(base_time + 15000),
            directory: "/scratch/user/biotech/md_sims/protein_folding_12".to_string(),
            command: "gromacs mdrun -s protein.tpr -deffnm output".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Failed,
            job_id: Some("pbs_987660".to_string()),
            end_time: Some(base_time + 16000),
            // FIXME exit_code: Some(1),
            archived: None,
        },
        Job {
            id: 8,
            job_name: "climate-model-2100".to_string(),
            config_id: 4,
            submit_time: Some(base_time + 20000),
            directory: "/scratch/user/climate/cesm_runs/scenario_rcp85".to_string(),
            command: "./cesm.exe --scenario RCP8.5 --years 2024-2100".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Failed,
            job_id: Some("pbs_987665".to_string()),
            end_time: Some(base_time + 21000),
            // FIXME exit_code: Some(255),
            archived: None,
        },
        // Timeout jobs
        Job {
            id: 9,
            job_name: "hyperparameter-search-xlarge".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 25000),
            directory: "/scratch/user/ml/hyperparam/search_space_v5".to_string(),
            command: "python optuna_search.py --trials 10000 --timeout 24h".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Timeout,
            job_id: Some("slurm_4891260".to_string()),
            end_time: Some(base_time + 111000),
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 10,
            job_name: "monte-carlo-financial".to_string(),
            config_id: 4,
            submit_time: Some(base_time + 30000),
            directory: "/scratch/user/finance/monte_carlo/risk_analysis_q4".to_string(),
            command: "python monte_carlo.py --simulations 1000000000 --instruments all".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Timeout,
            job_id: Some("pbs_987670".to_string()),
            end_time: Some(base_time + 117000),
            // FIXME exit_code: None,
            archived: Some(1),
        },
        // Running jobs
        Job {
            id: 11,
            job_name: "transformer-translation-multi".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 35000),
            directory: "/scratch/user/nmt/transformer/run_108".to_string(),
            command: "python train_nmt.py --src_lang en --tgt_langs fr,de,es,it,pt --model transformer-xl".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Running,
            job_id: Some("slurm_4891270".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 12,
            job_name: "alphafold-protein-complex".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 36000),
            directory: "/scratch/user/bioml/alphafold/complex_pred_045".to_string(),
            command: "python run_alphafold.py --fasta_paths complex.fasta --model_preset multimer".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Running,
            job_id: Some("slurm_4891271".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 13,
            job_name: "reinforcement-learning-atari".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 37000),
            directory: "/scratch/user/rl/dqn/atari_breakout_v12".to_string(),
            command: "python train_dqn.py --env BreakoutNoFrameskip-v4 --frames 50000000".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Running,
            job_id: Some("slurm_4891272".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 14,
            job_name: "genome-assembly-long-reads".to_string(),
            config_id: 3,
            submit_time: Some(base_time + 38000),
            directory: "/scratch/user/genomics/assembly/sample_hs_001".to_string(),
            command: "canu -p assembly -d output genomeSize=3.2g -nanopore reads.fastq.gz".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Running,
            job_id: Some("pbs_987680".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        // Queued jobs
        Job {
            id: 15,
            job_name: "neural-architecture-search".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 40000),
            directory: "/scratch/user/nas/search_space_v3/exp_022".to_string(),
            command: "python nas.py --search_space mobilenet --dataset cifar100 --budget gpu_hours=500".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Queued,
            job_id: Some("slurm_4891280".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 16,
            job_name: "federated-learning-medical".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 41000),
            directory: "/scratch/user/federated/medical_img/round_050".to_string(),
            command: "python fedavg.py --clients 100 --rounds 500 --model resnet50".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Queued,
            job_id: Some("slurm_4891281".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 17,
            job_name: "graph-neural-net-molecules".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 42000),
            directory: "/scratch/user/gnn/chemistry/drug_discovery_batch_8".to_string(),
            command: "python train_gnn.py --dataset zinc --model mpnn --layers 8".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Queued,
            job_id: Some("slurm_4891282".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 18,
            job_name: "time-series-forecasting-energy".to_string(),
            config_id: 4,
            submit_time: Some(base_time + 43000),
            directory: "/scratch/user/timeseries/energy_forecast/model_v8".to_string(),
            command: "python forecast.py --model temporal_fusion_transformer --horizon 168 --data energy_consumption.csv".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Queued,
            job_id: Some("pbs_987690".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 19,
            job_name: "speech-recognition-multilang".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 44000),
            directory: "/scratch/user/asr/whisper_ft/languages_20".to_string(),
            command: "python finetune_whisper.py --model large-v3 --languages all --hours 10000".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Queued,
            job_id: Some("slurm_4891283".to_string()),
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 20,
            job_name: "point-cloud-segmentation".to_string(),
            config_id: 2,
            submit_time: Some(base_time + 45000),
            directory: "/scratch/user/3d_vision/pointnet/urban_scenes".to_string(),
            command: "python train_pointnet.py --dataset semantic_kitti --backbone pointnet++".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::VirtualQueue,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        // Virtual Queue jobs
        Job {
            id: 21,
            job_name: "anomaly-detection-cybersec".to_string(),
            config_id: 4,
            submit_time: Some(base_time + 46000),
            directory: "/scratch/user/security/ids/network_traffic_v3".to_string(),
            command: "python train_autoencoder.py --data network_logs --window 24h".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::VirtualQueue,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 22,
            job_name: "recommendation-system-collab".to_string(),
            config_id: 3,
            submit_time: Some(base_time + 47000),
            directory: "/scratch/user/recsys/collaborative/movielens_100m".to_string(),
            command: "python train_ncf.py --dataset movielens-100m --embedding_dim 256".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::VirtualQueue,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        // Created but not submitted
        Job {
            id: 23,
            job_name: "text-generation-eval".to_string(),
            config_id: 5,
            submit_time: None,
            directory: "/home/user/dev/eval/text_gen_metrics".to_string(),
            command: "python evaluate_all.py --models gpt2,gpt3,llama --metrics bleu,rouge,bertscore".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Created,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        Job {
            id: 24,
            job_name: "data-preprocessing-cleanup".to_string(),
            config_id: 5,
            submit_time: None,
            directory: "/home/user/dev/data/cleaning_pipeline".to_string(),
            command: "python clean_dataset.py --input raw_data/ --output clean_data/ --workers 8".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::Created,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
        // Failed submission
        Job {
            id: 25,
            job_name: "distributed-training-1024gpu".to_string(),
            config_id: 1,
            submit_time: Some(base_time + 50000),
            directory: "/scratch/user/distributed/large_scale/attempt_02".to_string(),
            command: "python -m torch.distributed.launch --nproc_per_node=8 --nnodes=128 train_distributed.py".to_string(),
            preprocess: None,
            postprocess: None,
            variables: serde_json::from_str("null").unwrap(),
            status: Status::FailedSubmission,
            job_id: None,
            end_time: None,
            // FIXME exit_code: None,
            archived: None,
        },
    ];

  (jobs, configs, clusters)
}
