CREATE TABLE clusters (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  cluster_name TEXT NOT NULL UNIQUE,
  scheduler INTEGER NOT NULL,
  max_jobs INTEGER
);

CREATE TABLE configs (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  config_name TEXT NOT NULL,
  cluster_id INTEGER NOT NULL REFERENCES clusters(id) ON DELETE CASCADE,
  flags TEXT NOT NULL,
  env TEXT NOT NULL
);

CREATE TABLE jobs (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  job_name TEXT NOT NULL,
  config_id INTEGER NOT NULL REFERENCES configs(id) ON DELETE CASCADE,
  submit_time INTEGER,
  directory TEXT NOT NULL,
  command TEXT NOT NULL,
  status INTEGER NOT NULL,
  job_id TEXT,
  end_time INTEGER,
  preprocess TEXT,
  postprocess TEXT,
  archived INTEGER DEFAULT 0,
  variables TEXT NOT NULL
);

CREATE TABLE virtualqueue (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE
);