name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # ---- Format check ----
      - name: Check formatting
        run: cargo fmt --all -- --check
        continue-on-error: true

      # ---- Lint with Clippy ----
      - name: Run Clippy linter
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true

      # ---- Run tests ----
      - name: Run tests
        run: cargo test --all --verbose
        continue-on-error: true